<a href="https://colab.research.google.com/github/jiyeon00/gs-project/blob/ml/MLcode-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving dosirac.csv to dosirac.csv


In [ ]:
import io
dosirac= pd.read_csv(io.StringIO(uploaded['dosirac.csv'].decode('utf-8')))
dosirac

판매량  입고량  Unnamed: 2  ...  Unnamed: 29  Unnamed: 30  Unnamed: 31
0     4    6         NaN  ...          NaN          NaN          NaN
1     2    4         NaN  ...          NaN          NaN          NaN
2     5    6         NaN  ...          NaN          NaN          NaN
3     2    6         NaN  ...          NaN          NaN          NaN
4     0    3         NaN  ...          NaN          NaN          NaN
..  ...  ...         ...  ...          ...          ...          ...
57    6    9         NaN  ...          NaN          NaN          NaN
58    4    4         NaN  ...          NaN          NaN          NaN
59    7    8         NaN  ...          NaN          NaN          NaN
60    5    6         NaN  ...          NaN          NaN          NaN
61    3    5         NaN  ...          NaN          NaN          NaN

[62 rows x 32 columns]

In [ ]:
x_x = dosirac[['입고량']]
y_y = dosirac[['판매량']]
print(x_x)
print(y_y)

    입고량
0     6
1     4
2     6
3     6
4     3
..  ...
57    9
58    4
59    8
60    6
61    5

[62 rows x 1 columns]
    판매량
0     4
1     2
2     5
3     2
4     0
..  ...
57    6
58    4
59    7
60    5
61    3

[62 rows x 1 columns]


In [ ]:
x_x = x_x.to_numpy()
print(x_x)

[[ 6]
 [ 4]
 [ 6]
 [ 6]
 [ 3]
 [ 6]
 [ 6]
 [ 5]
 [ 3]
 [ 6]
 [ 6]
 [ 6]
 [ 4]
 [ 5]
 [ 4]
 [ 5]
 [ 5]
 [ 6]
 [ 6]
 [ 3]
 [ 6]
 [ 5]
 [ 5]
 [ 7]
 [ 5]
 [ 5]
 [ 6]
 [ 7]
 [ 6]
 [ 7]
 [ 6]
 [ 6]
 [ 7]
 [ 3]
 [ 5]
 [ 8]
 [ 7]
 [ 3]
 [ 6]
 [ 8]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 7]
 [ 5]
 [ 4]
 [ 5]
 [ 5]
 [ 6]
 [ 5]
 [ 6]
 [ 6]
 [ 5]
 [16]
 [ 4]
 [ 9]
 [ 9]
 [ 4]
 [ 8]
 [ 6]
 [ 5]]


In [ ]:
y_y = y_y.to_numpy()
print(y_y)

[[4]
 [2]
 [5]
 [2]
 [0]
 [5]
 [6]
 [5]
 [1]
 [2]
 [5]
 [3]
 [3]
 [1]
 [3]
 [3]
 [1]
 [4]
 [4]
 [2]
 [6]
 [5]
 [4]
 [7]
 [3]
 [2]
 [2]
 [5]
 [6]
 [7]
 [4]
 [3]
 [2]
 [3]
 [5]
 [6]
 [4]
 [3]
 [5]
 [6]
 [3]
 [2]
 [4]
 [6]
 [5]
 [3]
 [3]
 [3]
 [4]
 [4]
 [5]
 [6]
 [6]
 [5]
 [8]
 [4]
 [5]
 [6]
 [4]
 [7]
 [5]
 [3]]


In [ ]:
import numpy as np
input_ar = np.array(x_x)
target_ar = np.array(y_y)
print(input_ar.shape)
print(target_ar.shape)

(62, 1)
(62, 1)


In [ ]:
train_input = input_ar[:49]
train_target = target_ar[:49]
test_input = input_ar[49:]
test_target = target_ar[49:]
print(train_input.shape)
print(train_target.shape)



(49, 1)
(49, 1)


In [ ]:
train_ds = tf.data.Dataset.from_tensor

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(train_input,train_target)
print(lr.predict([[10]]))


[[7.38331678]]


In [ ]:
print(lr.coef_, lr.intercept_)

[[0.80983118]] [-0.71499503]


In [ ]:
train_poly = np.column_stack((train_input**2, train_input))
test_poly = np.column_stack((test_input**2, test_input))
print(train_poly.shape, test_poly.shape)

(49, 2) (13, 2)


In [ ]:
lr = LinearRegression()

lr.fit(train_poly,train_target)
print(lr.predict([[10**2,10]]))

[[8.28319657]]


In [ ]:
print(lr.coef_, lr.intercept_)

[[0.04512619 0.32708854]] [0.49969255]


In [ ]:
print(lr.score(train_poly, train_target))

0.4057369475200364
